# Generated by Django 2.2.5 on 2019-12-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluacionRespondida',
            new_name='Evaluacion',
        ),
    ]
