# Generated by Django 2.2.7 on 2019-11-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('nomGra', models.CharField(help_text='nombre del grado', max_length=15, primary_key=True, serialize=False)),
                ('nivGra', models.CharField(help_text='nivel del grado (primer ciclo, segundo ciclo, etc)', max_length=20)),
                ('seccion', models.CharField(help_text='Seccion del grado', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('codPro', models.CharField(help_text='codigo del profesor', max_length=15, primary_key=True, serialize=False)),
                ('nomPro', models.CharField(help_text='nombre del profesor', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('s', 'Profesor'), ('m', 'Medico')], default='sssssqqqqq', help_text='Tipo de usuario en el sistema', max_length=10),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codMat', models.CharField(help_text='codigo de la materia', max_length=15, primary_key=True, serialize=False)),
                ('nomMat', models.CharField(help_text='nombre de la materia', max_length=15)),
                ('graMat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Grado')),
                ('proMat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nieEst', models.IntegerField(help_text='Codigo del MINED asignado al estudiante', max_length=10, primary_key=True, serialize=False)),
                ('nomEst', models.CharField(help_text='Primer y/o segundo nombre del estudiante', max_length=20)),
                ('apeEst', models.CharField(help_text='Primer y/o segundo apellido del estudiante', max_length=20)),
                ('fecNac', models.DateField(blank=True)),
                ('nomPad', models.CharField(help_text='Nombre del padre', max_length=100)),
                ('nomMad', models.CharField(help_text='Nombre de la madre', max_length=100)),
                ('dirEst', models.CharField(help_text='Direccion del estudiante', max_length=100)),
                ('graEst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Grado')),
            ],
        ),
    ]
