# Generated by Django 2.2.7 on 2019-11-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0002_auto_20191114_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('numDep', models.IntegerField(primary_key=True, serialize=False)),
                ('nomDep', models.CharField(help_text='Ingrese un departamento', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('duiMad', models.CharField(help_text='Codigo de la madre', max_length=10, primary_key=True, serialize=False)),
                ('nomMad', models.CharField(help_text='Nombre de la madre', max_length=100)),
                ('dirMad', models.CharField(help_text='Direccion de la madre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('duiPad', models.CharField(help_text='Codigo del padre', max_length=10, primary_key=True, serialize=False)),
                ('nomPad', models.CharField(help_text='Nombre del padre', max_length=100)),
                ('dirPad', models.CharField(help_text='Direccion del padre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('duiRep', models.CharField(help_text='Codigo del padre', max_length=10, primary_key=True, serialize=False)),
                ('nomRep', models.CharField(help_text='Nombre del padre', max_length=100)),
                ('dirRep', models.CharField(help_text='Direccion del representante', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nomMad',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nomPad',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='proMat',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='edadEst',
            field=models.IntegerField(blank=True, help_text='Edad actual del estudiante', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('p', 'Profesor'), ('s', 'Secretaria'), ('e', 'Estudiante'), ('d', 'Docente'), ('d', 'Orientador')], default='sssssqqqqq', help_text='Tipo de usuario en el sistema', max_length=10),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('numReg', models.IntegerField(help_text='numero de registro', primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, help_text='nota del estudiante', max_digits=4)),
                ('ponNot', models.DecimalField(decimal_places=2, help_text='ponderacion del estudiante', max_digits=3)),
                ('tipo_nota', models.CharField(blank=True, choices=[('n', 'normal'), ('r', 'reposicion')], default='sssssqqqqq', help_text='Tipo de notadel estudiante', max_length=10)),
                ('notEst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Estudiante')),
                ('notMat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Materia')),
                ('notPro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('numMunicipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nomMunicipio', models.CharField(help_text='Ingrese un municipio', max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon.Departamento')),
            ],
        ),
    ]
