# Generated by Django 2.2.5 on 2019-12-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0002_auto_20191202_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='totalE',
            field=models.IntegerField(null=True),
        ),
    ]
