# Generated by Django 2.2.7 on 2019-11-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0003_auto_20191118_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='estado',
            field=models.CharField(blank=True, choices=[('a', 'activo'), ('i', 'inactivo')], default='a', help_text='Tipo de usuario en el sistema', max_length=10),
        ),
        migrations.AddField(
            model_name='registro',
            name='periodo',
            field=models.CharField(blank=True, choices=[('1', '1er periodo'), ('2', '2do periodo'), ('3', '3er periodo'), ('4', '4to periodo')], default='1', help_text='Tipo de nota del estudiante', max_length=15),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edadEst',
            field=models.IntegerField(blank=True, help_text='Edad actual del estudiante', null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nieEst',
            field=models.IntegerField(help_text='Codigo del MINED asignado al estudiante', primary_key=True, serialize=False),
        ),
    ]
