# Generated by Django 2.2.5 on 2019-12-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0003_auto_20191202_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admon.Estudiante'),
        ),
    ]
