# Generated by Django 2.2.5 on 2019-11-19 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0004_auto_20191118_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDocente',
            fields=[
                ('numEva', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaE', models.DateField(blank=True)),
                ('valPreg0', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('valPreg1', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('valPreg2', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('valPreg3', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('valPreg4', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('valPreg5', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('valPreg6', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('valPreg7', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('valPreg8', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('valPreg9', models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], help_text='Seleccione un valor')),
                ('totalE', models.IntegerField()),
                ('profes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Profesor')),
            ],
        ),
    ]
