# Generated by Django 2.2.5 on 2019-11-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0005_evaluaciondocente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluaciondocente',
            old_name='fechaE',
            new_name='fecVen',
        ),
        migrations.AddField(
            model_name='evaluaciondocente',
            name='estado',
            field=models.IntegerField(default=0, help_text='0 -> Pendiente, 1-> Realizada'),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='numEva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg0',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg1',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg2',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg3',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg4',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg5',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg6',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg7',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg8',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg9',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True),
        ),
    ]
