# Generated by Django 2.2.5 on 2019-11-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0006_auto_20191123_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendiente'), (2, 'Finalizada')], default=1),
        ),
    ]
