# Generated by Django 2.2.5 on 2019-11-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0007_auto_20191123_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='totalE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
