# Generated by Django 2.2.5 on 2019-11-25 21:51

import admon.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0008_auto_20191125_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='fecVen',
            field=models.DateField(blank=True, validators=[admon.validators.fecha_Mayor_Que_Hoy]),
        ),
    ]
