# Generated by Django 2.2.5 on 2019-11-27 00:27

import admon.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0009_auto_20191125_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='fecVen',
            field=models.DateField(validators=[admon.validators.fecha_Mayor_Que_Hoy]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='profes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Profesor'),
        ),
    ]
