# Generated by Django 2.2.5 on 2019-11-27 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0010_auto_20191126_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='profes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon.Profesor'),
        ),
    ]
