# Generated by Django 2.2.7 on 2019-12-03 20:02

import admon.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0011_auto_20191126_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('numReg', models.IntegerField(help_text='numero de registro', primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, help_text='nota del estudiante', max_digits=4)),
                ('tipo_nota', models.CharField(blank=True, choices=[('n', 'normal'), ('r', 'reposicion')], default='n', help_text='Tipo de notadel estudiante', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('numMes', models.IntegerField(primary_key=True, serialize=False)),
                ('nomMes', models.CharField(max_length=15)),
                ('anio', models.CharField(help_text='año del Mes', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('codSec', models.CharField(help_text='codigo del profesor', max_length=15, primary_key=True, serialize=False)),
                ('nomSec', models.CharField(help_text='nombre del profesor', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Usuario'),
        ),
        migrations.AddField(
            model_name='grado',
            name='anio',
            field=models.DateField(help_text=' ', null=True),
        ),
        migrations.AddField(
            model_name='grado',
            name='orientador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Profesor'),
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Usuario'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codPro',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='estado',
            field=models.CharField(blank=True, choices=[('a', 'activo'), ('i', 'inactivo')], default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nomPro',
            field=models.CharField(max_length=100, validators=[admon.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('p', 'Profesor'), ('s', 'Secretaria'), ('e', 'Estudiante'), ('a', 'Administrador'), ('o', 'Orientador')], default='e', help_text='Tipo de usuario en el sistema', max_length=10),
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AddField(
            model_name='secretaria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Usuario'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Estudiante'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Grado'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Mes'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='notEst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Estudiante'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='notMat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon.Materia'),
        ),
    ]
