# Generated by Django 2.2.7 on 2019-12-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0012_auto_20191203_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='estudiantes',
            field=models.ManyToManyField(to='admon.Estudiante'),
        ),
    ]
