# Generated by Django 2.2.5 on 2019-11-30 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0012_estudiante_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
