# Generated by Django 2.2.5 on 2019-11-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0013_registro_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
