# Generated by Django 2.2.7 on 2019-12-03 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0014_auto_20191203_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='estudiantes',
        ),
    ]
