# Generated by Django 2.2.5 on 2019-12-01 17:18

import admon.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0014_auto_20191129_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg0',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg1',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg2',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg3',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg4',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg5',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg6',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg7',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg8',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='valPreg9',
            field=models.IntegerField(blank=True, choices=[(1, 'Necesita Mejorar'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], null=True, validators=[admon.validators.no_Respondido]),
        ),
    ]
