# Generated by Django 2.2.5 on 2019-12-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0015_auto_20191201_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondocente',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon.Estudiante'),
        ),
    ]
