# Generated by Django 2.2.7 on 2019-12-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0016_materia_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='estudiantes',
        ),
    ]
