# Generated by Django 2.2.7 on 2019-12-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0017_remove_materia_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='seccion',
        ),
    ]
