# Generated by Django 2.2.7 on 2019-12-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0018_remove_grado_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='admon.Estudiante'),
        ),
    ]
