# Generated by Django 2.2.7 on 2019-12-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0019_materia_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='materias',
            field=models.ManyToManyField(blank=True, to='admon.Materia'),
        ),
    ]
