# Generated by Django 2.2.7 on 2019-12-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0021_remove_materia_gramat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='anio',
            field=models.CharField(help_text=' ', max_length=4),
        ),
    ]
