# Generated by Django 2.2.7 on 2019-12-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0022_auto_20191203_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='graEst',
        ),
    ]
