# Generated by Django 2.2.7 on 2019-12-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0024_auto_20191203_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='codMat',
            field=models.CharField(help_text='codigo de la materia', max_length=15, primary_key=True, serialize=False),
        ),
    ]
