# Generated by Django 2.2.7 on 2019-12-04 03:27

import admon.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon', '0026_auto_20191203_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='nomGra',
            field=models.CharField(help_text='nombre del grado', max_length=15, primary_key=True, serialize=False, validators=[admon.validators.solo_Letras]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codMat',
            field=models.CharField(help_text='codigo de la materia', max_length=15, primary_key=True, serialize=False),
        ),
    ]
